### ISSUE TITLE
[FEATURE] Why does recording a video automatically end after just over 30 minutes? Is there any solution?

### ISSUE THREAD

**Issue by rabbit07072** [anonfaded/FadCam#72]
Why does recording a video automatically end after just over 30 minutes? Is there any solution?

**Comment by anonfaded** [comment]
> Why does recording a video automatically end after just over 30 minutes? Is there any solution?

You are very likely using older version from F-Droid where this bug was present but fixed later.
The latest version is only on GitHub for now, so please download the latest beta version from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.1-beta 
And then let me know if your issue is fixed, Thanks!

**Comment by rabbit07072** [comment]
thanks
